sudo: required
services:
  - docker

before_install:
  - docker build -t vroxo/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true vroxo/docker-react-app npm run test -- --coverage

